### ISSUE TITLE
[Feature Request] Create collection with initial data

### ISSUE THREAD

**Issue by dungngminh** [danReynolds/loon#13]
## Context
- Hi there, your package is so nice, I found it in X so I tried to apply it to my project and it matched my current expectations for a new document type local database, easy to use and easy to sync to Firebase.
- Currently, I have a concern when I implement feature that need default or initial data when the user first app install, I found out that package's document doesn't mention about how to init default data when we first app install like creating a database from the default db file or something else. Are you have any idea for it?

## Current temporary solution
 - I added some code to `Loon.hydrate()` after Loon loaded saved data, like this
```dart
 Loon.hydrate().then((_) {
    log('Hydration complete');
    final defaultPlantSiteDoc =
        LocalPlantSite.plantSiteStore.doc(kDefaultPlantSiteKey);
    final isDefaultPlantSiteExists = defaultPlantSiteDoc.exists();
    if (!isDefaultPlantSiteExists) {
      defaultPlantSiteDoc.create(defaultPlantSite);
      log('Default plant site created');
    }
  });
```
## Expectation

- I want to know an effective way for creating a collection that it has initial data when user first app install

Thanks and have a great day 🚀

**Comment by danReynolds** [comment]
Hello there! Thanks for reaching out. In my app what I do is store a boolean like `isFirstLaunch` which could be stored in shared_preferences or any other persistence mechanisms. If you're using `Loon` persistence, you could store whether it's first launch as a one-off document like this:

```dart
Future<void> main() async {
  Loon.configure(persistor: FilePersistor());
  
  await Loon.hydrate();

  final launchSnap = Loon.doc('isFirstLaunch').get();

  if (launchSnap == null) {
    // Initialize your data and then mark first launch false
    Loon.doc('isFirstLaunch').create(false);
  }
}
```

I think that's pretty straightforward, but let me know what you think.

**Comment by dungngminh** [comment]
I think I have a better way to load my first initial data from your suggestion 🚀 Thanks for your suggestion.

**Comment by danReynolds** [comment]
Sounds good!
